config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "about", to: "pages#about"
  resources :articles

  get "signup", to: "users#new"
  # post "users", to: "users#create"
  resources :users, except: [:new]

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: {minimum: 5, maximum: 30}
  validates :body, presence: true, length: {minimum: 10, maximum: 10000}
end

app/models/user.rb
class User < ApplicationRecord
  before_save {self.email = email.downcase}
  has_many :articles, dependent: :destroy
  validates :username, presence: true, uniqueness: {case_sensitive: false},
                       length: {minimum: 3, maximum:25}
  
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: {case_sensitive: false},
                    length: {maximum:105},
                    format: {with: VALID_EMAIL_REGEX}
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?
    #as this current_user method is defined in application controller,
    #so we can not use it in our views so to access it in our view,
    # we have declared it as a helper method now we can access it in both,
    #our views and controllers
    
    def current_user
        # if session[:user_id]
        #   user.find(session[:user_id])
        
        # antther short method to write the aboe code is
        # user.find(session[:user_id]) if session[:user_id]
        
        # on every time when will refer this method it will hit the data base
        # and that is not the efficient way to so will perform this as
        @current_user ||= User.find(session[:user_id]) if session[:user_id]      # so in above scenerio if we have already current user then it will
        # retrun it other wise will hit the data base and will return the current
        # user
    end

    def logged_in?
        # to check logged in we have to simply check the current user exist so for that
        # we have to turn user into boolean
        !!current_user
        # if it has a current user it wil return true else flase
    end

    def require_user
      if !logged_in?
        flash[:alert] = "You must Log In First"
        redirect_to login_path
      end
    end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only:[:show, :edit, :update, :destroy]
  before_action :require_user, except:[:show, :index]
  before_action :require_same_user, only:[:edit, :update, :destroy]
  
  def show
  end 
    
  def index
    @articles = Article.paginate(page: params[:page], per_page: 4)

  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(art_params)
    @article.user = current_user
    if @article.save
      flash[:notice]="Article Created Successfully"
      redirect_to @article
    else
      render 'new', status: :unprocessable_entity
    end
  end

  def update
    if @article.update(art_params)
      flash[:notice] = "Article Updated Successfully"
      redirect_to @article
    else
      render "new", status: :unprocessable_entity
    end

  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end


  private
    
    def find_article
      @article = Article.find(params[:id])
    end

    def art_params
      params.require(:article).permit(:title, :body)
    end

    def require_same_user
      if current_user != @article.user && !current_user.admin?
        flash[:alert] = "You can only Edit, Update, or Delete your own Article"
        redirect_to @article
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to articles_path if logged_in?
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
   before_action :check_login, only:[:new, :create]
  
  
  
  def new
  end

  def create
    # byebug
    user = User.find_by(email: params[:sessions][:email].downcase)
    if user && user.authenticate(params[:sessions][:password])
      session[:user_id] = user.id
      flash[:notice] = "logged in Successfully"
      redirect_to user
    else
      flash.now[:alert] = "Incorrect Email or Password"
      render "new"
    end
        
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "Successfully logged Out"
    redirect_to root_path
  end

  private
    
    def check_login
      if logged_in?
        flash[:alert] = "You cannot login again, Must logout First"
        redirect_to root_path
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only:[:show, :edit, :update, :destroy]
  before_action :require_user, only:[:edit, :update]
  before_action :require_same_user, only:[:edit, :update, :destroy]


  def index
    @users = User.paginate(page: params[:page], per_page: 4)
  end

  def show
    @articles = @user.articles.paginate(page: params[:page], per_page: 4)
  end
  
  def new
    @user = User.new
  end

  def edit
  end

  def create
    @user = User.new(user_params)
    if @user.save
      # we have used here instance user method to automatically login the user
      # after his signup
      session[:user_id] = @user.id
      flash[:notice] = "Welcome To Iftikhar Blog! #{@user.username} You have Successfully Signed Up"
      redirect_to articles_path
    else
        render "new"
    end
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your Account Successfully Updated"
      redirect_to @user
    else
      render "edit"
    end
  end

  def destroy
    @user.destroy
    session[:user_id] = nil if @user == current_user
    flash[:notice] = "Account and all Associated Artilces deleted"
    redirect_to articles_path
  end

  private
    
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

    def find_user
      @user = User.find(params[:id])
    end

    def require_same_user
      if current_user != @user && !current_user.admin?
        flash[:alert] = "You can only Update, or Delete your own Account"
        redirect_to @user
      end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
   #current _user method is defined in application controller
   #loggen_in? method is defined in application controller
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<div class="container">

  <% if @article.errors.any? %>
    <% @article.errors.full_messages.each do |msg|%>
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
         <%=msg%>
         <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <%end%>
  <%end%>







  <div class="card mt-4">
    <div class="card-header text-center fw-bolder">
      <%= ne%> Article
    </div>
    <div class="card-body">
      <%= form_with(model: @article, local: true ) do |f|%>
      <%# <form> %>
        <div class="mb-3">
          <%= f.label :title, class:"form-label"%><br>
          <%= f.text_field :title, class:"form-control"%>
          <%# <label for="exampleInputEmail1" class="form-label">Title of Article</label> %>
          <%# <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"> %>
        </div>
        <div class="mb-3">
          <%= f.label :body, class:"form-label"%><br>
          <%# <label for="exampleInputPassword1" class="form-label">Description of Article</label> %>
          <%= f.text_area :body, rows: 10, class:"form-control"%>
          <%# <input type="password" class="form-control" id="exampleInputPassword1"> %>
        </div>
        
        <div class="text-center">
          <%= f.submit class:"btn btn-secondary text-center"%>
          <%# <button type="submit" class="btn btn-primary text-center">Submit</button> %>
        </div>
      <%# </form> %>
      <%end%>
      <br>
      <div class="text-center">
        <%= link_to "Cancel",articles_path, class:"btn btn-secondary text-center", id:"cancel-button"%>
      </div>
    </div>
  </div>
</div>

app/views/articles/_pagination.html.erb
<div class="apple_pagination mb-4 mt-2">
    <div class="page_info">
      <%= page_entries_info obj %>
    </div>
    <%= will_paginate obj, :container => false %>
  </div>

app/views/articles/edit.html.erb
<%= render "form", ne:"Edit"%>

app/views/articles/index.html.erb
<div class="container text-center">
  <h1>List of Articles</h1>
  <%= render "pagination", obj: @articles %>
  <div class="row row-cols-1 row-cols-md-2 g-4">
    <% @articles.each do |article|%>
      <div class="col">
        <div class="row justify-content-md-center">
          <div class= "col-8 mt-4">
            <div class="card  text-center shadow-lg  mb-5 bg-body rounded">
              <div class="card-header text-white bg-dark border-dark fst-italic">
                by <%= article.user.username%>
              </div>
              <div class="card-body border-dark">
                <h5 class="card-title"><%= article.title%></h5>
                <p class="card-text"> <%= truncate(article.body, length:50)%></p>
                <%= link_to "Show", article_path(article), class: "btn btn-info"%>
                <% if logged_in? && (article.user == current_user || current_user.admin?)%>
                  <%= link_to "Edit", edit_article_path(article), class: "btn btn-secondary"%>
                  <%= link_to "Delete", article_path(article), class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure"}%>
                  <%# <a href="#" class="btn btn-primary">Go somewhere</a> %>
                <%end%>
              </div>
              <div class="card-footer text-muted text-white bg-dark border-dark">
                <small>Created at: <%= time_ago_in_words(article.created_at)%> ago</small><br>
                <small>Updated at: <%= time_ago_in_words(article.updated_at)%> ago</small>
              </div>
            </div>
          </div>  
        </div>
      </div>  
    <%end%>
  </div>
  <%= render "pagination", obj: @articles %>
  <p><%= link_to "Create New Article",new_article_path, class:"btn btn-secondary text-center"%></p>
</div>

app/views/articles/new.html.erb
<%= render "form", ne:" Create New"%>

app/views/articles/show.html.erb
<div class="container text-center">
  <h2><%= @article.title%></h2>
        <div class="row justify-content-md-center">
          <div class= "col-8 mt-4">
            <div class="card  text-center shadow-lg  mb-5 bg-body rounded">
              <div class="card-header text-white bg-dark border-dark fst-italic">
                by <%= @article.user.username%>
              </div>
              <div class="card-body border-dark">
                <div class="card-text text-start"> <%= simple_format(@article.body)%></div>
                <% if logged_in? && (@article.user == current_user || current_user.admin?)%>
                  <%= link_to "Edit", edit_article_path(@article), class: "btn btn-secondary"%>
                  <%= link_to "Delete", article_path(@article), class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure"}%>
                <%end%>
                <%= link_to "Back to Articles", articles_path, class: "btn btn-primary"%>
              </div>
              <div class="card-footer text-muted text-white bg-dark border-dark">
                <small>Created at: <%= time_ago_in_words(@article.created_at)%> ago</small><br>
                <small>Updated at: <%= time_ago_in_words(@article.updated_at)%> ago</small>
              </div>
            </div>
          </div>  
        </div>
  <p><%= link_to "Create New Article",new_article_path, class:"btn btn-secondary text-center"%></p>
</div>

app/views/layouts/_errorMessages.html.erb
<div class="container mt-2">
  <% flash.each do |keyname, msg|%>
    <% if keyname == "notice" %>
      <div class="alert alert-success alert-dismissible fade show" role="alert">
        <%= msg%>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% else%>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <%= msg%>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <%end%>  
  <%end%>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Ifitkhar Blog", root_path, class:"navbar-brand"%>
    <%# <a class="navbar-brand" href="#">Iftikhar Blog</a> %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Bloggers", users_path, class: "nav-link"%>
          <%# <a class="nav-link" href="#">Link</a> %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "View all Articles", articles_path, class:"dropdown-item"%>
            <%# <li><a class="dropdown-item" href="#">Action</a></li> %>
            <% if logged_in?%>
              <%= link_to "Create New Article", new_article_path, class:"dropdown-item"%>
            <%end%>
            <%# <li><a class="dropdown-item" href="#">Another action</a></li> %>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <% if logged_in?%>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= ("Admin ") if current_user.admin? %><%= current_user.username%>
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "View your Profile", user_path(current_user), class:"dropdown-item"%>
              <%# <li><a class="dropdown-item" href="#">Action</a></li> %>
              <%= link_to "Update your Profile", edit_user_path(current_user), class:"dropdown-item"%>
              <%# <li><a class="dropdown-item" href="#">Another action</a></li> %>
              <%= link_to "Delete Profile", user_path(current_user), class:"dropdown-item text-danger", method: :delete, data:{confirm: "Are you Sure"}%>

            </ul>
          </li>
          <li class="nav-item">
          <%= link_to "Log Out", logout_path, method: :delete,class: "nav-link"%>
          <%# <a class="nav-link disabled">Disabled</a> %>
          </li>
        <%else%>
          <li class="nav-item">
          <%= link_to "Log In", login_path,class: "nav-link"%>
          <%# <a class="nav-link disabled">Disabled</a> %>
          </li>
          <li class="nav-item">
          <%= link_to "Sign Up", signup_path, class:"nav-link"%>
          <%# <a class="nav-link disabled">Disabled</a> %>
          </li>
        <%end%>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-secondary" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IftikharBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <%= render "layouts/navbar"%>
    <%= render "layouts/errorMessages"%>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Page</h1>
<%= link_to "Articles Listing", articles_path%> | <%= link_to "HOme Page", root_path%>

app/views/pages/home.html.erb
<div class="container">
  <div class="jumbotron text-center">
    <h1 class="display-4">Iftikhar's Blog!</h1>
    <p class="lead">You Find the stuff here, You want!.</p>
    <hr class="my-4">
    <p>The hub of Knowledge.</p>
    <%# <h1>Home Page</h1> %>
    <% if logged_in? == false %>
    <%= link_to "Sign Up", signup_path, class:"btn btn-secondary"%> 
    <%# <a class="btn btn-secondary" href="#" role="button">Sign Up</a> %>
    <%end%>
  </div>
</div>

<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; Iftikhar Blog</small>
  </div>
</footer>

app/views/users/_form.html.erb
<div class="container">

  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |msg|%>
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
         <%=msg%>
         <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <%end%>
  <%end%>







  <div class="card mt-4">
    <div class="card-header text-center fw-bolder">
      <%= ne%>
    </div>
    <div class="card-body">
      <%= form_with(model: @user, local: true ) do |f|%>
      <%# <form> %>
        <div class="mb-3">
          <%= f.label :username, class:"form-label"%><br>
          <%= f.text_field :username, class:"form-control"%>
          <%# <label for="exampleInputEmail1" class="form-label">Title of Article</label> %>
          <%# <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"> %>
        </div>
        <div class="mb-3">
          <%= f.label :email, class:"form-label"%><br>
          <%# <label for="exampleInputPassword1" class="form-label">Description of Article</label> %>
          <%= f.email_field :email, class:"form-control"%>
          <%# <input type="password" class="form-control" id="exampleInputPassword1"> %>
        </div>
        <div class="mb-3">
          <%= f.label :password, class:"form-label"%><br>
          <%# <label for="exampleInputPassword1" class="form-label">Description of Article</label> %>
          <%= f.password_field :password, class:"form-control"%>
          <%# <input type="password" class="form-control" id="exampleInputPassword1"> %>
        </div>
        
        <div class="text-center">
          <%= f.submit ne2, class:"btn btn-secondary text-center"%>
          <%# <button type="submit" class="btn btn-primary text-center">Submit</button> %>
        </div>
      <%# </form> %>
      <%end%>
      <br>
      <div class="text-center">
        <%= link_to "Cancel",articles_path, class:"btn btn-secondary text-center", id:"cancel-button"%>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<%= render "form", ne:"Edit Your Profile", ne2: "Update User"%>

app/views/users/index.html.erb
<div class="container text-center">
  <h2>List of Iftikhar-Blog's Users</h2>
  <%= render "articles/pagination", obj: @users%>
  <div class="row row-cols-1 row-cols-md-2 g-4">
    <% @users.each do |user|%>
      <div class="col">
        <div class="row justify-content-md-center">
          <div class= "col-8 mt-4">
            <div class="card  text-center shadow-lg  mb-5 bg-body rounded">
              <div class="card-header text-white bg-dark border-dark fst-italic">
                <%= user.username%>
              </div>
              <div class="card-body border-dark">
                <h5 class="card-title"><%= user.username%> has:</h5>
                <p class="card-text"><%= pluralize(user.articles.count, "Article")%></p>
                <%= link_to "Show Profile", user_path(user), class: "btn btn-info"%>
                <% if logged_in?%>
                  <% if user == current_user%>
                  <%= link_to "Edit Profile", edit_user_path(user), class: "btn btn-secondary"%>
                  <%# <a href="#" class="btn btn-primary">Go somewhere</a> %>
                  <%end%>
                  <% if current_user.admin?%>
                    <%= link_to "Delete user", user_path(user), class: "btn btn-secondary mt-1", method: :delete, 
                                data:{confirm: "Are you Sure to Delete This User"}%>
                  <%end%>
                <%end%>
              </div>
              <div class="card-footer text-muted text-white bg-dark border-dark">
                <small>Joined: <%= time_ago_in_words(user.created_at)%> ago</small><br>
              </div>
            </div>
          </div>  
        </div>
      </div>  
    <%end%>
  </div>
  <%= render "articles/pagination", obj: @users%>
  <p><%= link_to "Create New User",signup_path, class:"btn btn-secondary text-center"%></p>
</div>

app/views/users/new.html.erb
<%= render "form", ne:" Sign Up", ne2: "Sign Up"%>

app/views/users/show.html.erb
<div class="container text-center">
  <h2>User Profile</h2>
  <h5><%= @user.username%></h5> 
  <h6><%= @user.email%></h6>
  <% if logged_in? && @user == current_user%>
    <%= link_to "Update User Profile", edit_user_path(@user), class: "btn btn-secondary"%>
  <%end%>
  <%= render "articles/pagination", obj: @articles%> 
  <% if @user.articles.any? == true%>
  <h4>List of Articles created by <%= @user.username%></h4>
  <div class="row row-cols-1 row-cols-md-2 g-4">
      <% @articles.each do |article|%>
        <div class="col">
          <div class="row justify-content-md-center">
            <div class= "col-8 mt-4">
              <div class="card  text-center shadow-lg  mb-5 bg-body rounded">
                <div class="card-header text-white bg-dark border-dark fst-italic">
                    by <%= article.user.username%>
                </div>
                <div class="card-body border-dark">
                    <h5 class="card-title"><%= article.title%></h5>
                    <p class="card-text"> <%= truncate(article.body, length:50)%></p>
                    <%= link_to "Show", article_path(article), class: "btn btn-info"%>
                    <% if logged_in? && article.user == current_user%>
                      <%= link_to "Edit", edit_article_path(article), class: "btn btn-secondary"%>
                      <%= link_to "Delete", article_path(article), class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure"}%>
                      <%# <a href="#" class="btn btn-primary">Go somewhere</a> %>
                    <%end%>
                </div>
                <div class="card-footer text-muted text-white bg-dark border-dark">
                    <small>Created at: <%= time_ago_in_words(article.created_at)%> ago</small><br>
                    <small>Updated at: <%= time_ago_in_words(article.updated_at)%> ago</small>
                </div>
              </div>
            </div>  
          </div>
        </div>  
      <%end%>
  </div>
  <% else %>
    <%= "No Articles Found"%>
  <% end%>
  <%= render "articles/pagination", obj: @articles%>
  <%if logged_in? && @user == current_user%>
    <p><%= link_to "Create New Article",new_article_path, class:"btn btn-secondary text-center"%></p>
  <%end%>
</div>